service: python-pptx-lambda
frameworkVersion: '2'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    cacheLocation: ".static_cache"
    dockerizePip: true
    # layer: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:*
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: PresentationBucket
                - '/*'

package:
  patterns:
    - '!*/**'
    - '*.py'

functions:
  Scratch:
    handler: handler.scratch
    # layers:
    #   - Ref: PythonRequirementsLambdaLayer
    environment:
      BUCKET_NAME: !Ref PresentationBucket


resources:
  Resources:
    PresentationBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub python-pptx-lambda-${AWS::AccountId}
